# Default Categories!
Category.create(name: '2 in 1', slug: '2_in_1')
Category.create(name: 'All in One', slug: 'all_in_one')
Category.create(name: 'Classmate PC', slug: 'classmate_pc')
Category.create(name: 'Desktop', slug: 'desktop')
Category.create(name: 'Events', slug: 'events')
Category.create(name: 'Internet of Things', slug: 'internet_of_things_1')
Category.create(name: 'Kits', slug: 'kits_1')
Category.create(name: 'Multicast', slug: 'multicast')
Category.create(name: 'Notebook', slug: 'notebook')
Category.create(name: 'NUC', slug: 'nuc')
Category.create(name: 'Server', slug: 'server')
Category.create(name: 'Services', slug:  'services')
Category.create(name: 'Solutions_and_Demos', slug: 'solutions_and_demos')
Category.create(name: 'Special Approval Pool', slug: 'special_approval_pool')
Category.create(name: 'Tablet', slug: 'tablet')
Category.create(name: 'TME Work Space', slug: 'tme_work_space')
Category.create(name: 'Ultrabook', slug: 'ultrabook')