# Default Categories!
Category.create(is_enabled: 1, name: '2 in 1', slug: '2_in_1')
Category.create(is_enabled: 1, name: 'All in One', slug: 'all_in_one')
Category.create(is_enabled: 1, name: 'Classmate PC', slug: 'classmate_pc')
Category.create(is_enabled: 1, name: 'Desktop', slug: 'desktop')
Category.create(is_enabled: 1, name: 'Events', slug: 'events')
Category.create(is_enabled: 1, name: 'Internet of Things', slug: 'internet_of_things_1')
Category.create(is_enabled: 1, name: 'Kits', slug: 'kits')
Category.create(is_enabled: 1, name: 'Multicast', slug: 'multicast')
Category.create(is_enabled: 1, name: 'Notebook', slug: 'notebook')
Category.create(is_enabled: 1, name: 'NUC', slug: 'nuc')
Category.create(is_enabled: 1, name: 'Server', slug: 'server')
Category.create(is_enabled: 1, name: 'Services', slug:  'services')
Category.create(is_enabled: 1, name: 'Solutions_and_Demos', slug: 'solutions_and_demos')
Category.create(is_enabled: 1, name: 'Special Approval Pool', slug: 'special_approval_pool')
Category.create(is_enabled: 1, name: 'Tablet', slug: 'tablet')
Category.create(is_enabled: 1, name: 'TME Work Space', slug: 'tme_work_space')
Category.create(is_enabled: 1, name: 'Ultrabook', slug: 'ultrabook')

Pool.create(is_enabled: 1, name: "USDD" )
Pool.create(is_enabled: 1, name: "APAC" )
Pool.create(is_enabled: 1, name: "SAP" )
Pool.create(is_enabled: 1, name: "Intel_Education" )
Pool.create(is_enabled: 1, name: "ASEP" )
Pool.create(is_enabled: 1, name: "PCSD" )
Pool.create(is_enabled: 1, name: "ABCD" )
Pool.create(is_enabled: 1, name: "DCG_VMW_GTM" )
Pool.create(is_enabled: 1, name: "ARPS" )
Pool.create(is_enabled: 1, name: "ETSP" )
Pool.create(is_enabled: 1, name: "VCA" )
Pool.create(is_enabled: 1, name: "MIP" )
Pool.create(is_enabled: 1, name: "IEM" )
Pool.create(is_enabled: 1, name: "RSD" )
Pool.create(is_enabled: 1, name: "STLP" )
Pool.create(is_enabled: 1, name: "EXTERNAL" )
Pool.create(is_enabled: 1, name: "IOTG" )
Pool.create(is_enabled: 1, name: "PSMSP" )

Ose.create(is_enabled: 1, name: "Linux | Wind River" )
Ose.create(is_enabled: 1, name: "Linux | Ubuntu" )
Ose.create(is_enabled: 1, name: "Linux | CentOS" )
Ose.create(is_enabled: 1, name: "Win 7 Ent | 32-Bit | KMS " )
Ose.create(is_enabled: 1, name: "Win 7 Pro | 64-Bit | KMS" )
Ose.create(is_enabled: 1, name: "Win 7 Pro | 64-Bit | OEM" )
Ose.create(is_enabled: 1, name: "Win 7 Ent | 64-Bit | KMS" )
Ose.create(is_enabled: 1, name: "Win 8.1 | 32-Bit | OEM" )
Ose.create(is_enabled: 1, name: "Win 8.1 | 64-Bit | OEM" )
Ose.create(is_enabled: 1, name: "Win 8.1 w/ Bing | 64-Bit | OEM" )
Ose.create(is_enabled: 1, name: "Win 8.1 w/ Bing | 32-Bit | OEM" )
Ose.create(is_enabled: 1, name: "Win 8.1 Pro | 64-Bit | OEM" )
Ose.create(is_enabled: 1, name: "Win 8.1 Pro | 32-Bit | OEM" )
Ose.create(is_enabled: 1, name: "Win 8.1 Pro | 64-Bit | KMS" )
Ose.create(is_enabled: 1, name: "Win 8.1 Pro | 32-Bit | KMS" )
Ose.create(is_enabled: 1, name: "Win 8.1 Ent | 32-Bit | KMS" )
Ose.create(is_enabled: 1, name: "Win 8.1 Ent | 64-Bit | KMS" )
Ose.create(is_enabled: 1, name: "Win 8.1 Ent | 64-Bit | MAK" )
Ose.create(is_enabled: 1, name: "Win 8.1 Ent | 32-Bit | MAK" )
Ose.create(is_enabled: 1, name: "Win 2012R2 Data Update | KMS" )
Ose.create(is_enabled: 1, name: "Win 2012R2 Data | KMS" )
Ose.create(is_enabled: 1, name: "Win 2012R2 Std | KMS" )
Ose.create(is_enabled: 1, name: "Win 10 Home | 64-Bit | OEM" )
Ose.create(is_enabled: 1, name: "Win 10 Home | 32-Bit | OEM" )
Ose.create(is_enabled: 1, name: "Win 10 Home | 64-Bit | Upgrade (OEM)" )
Ose.create(is_enabled: 1, name: "Win 10 Home | 32-Bit | Upgrade (OEM)" )
Ose.create(is_enabled: 1, name: "Win 10 Pro | 64-Bit | OEM" )
Ose.create(is_enabled: 1, name: "Win 10 Pro | 32-Bit | OEM" )
Ose.create(is_enabled: 1, name: "Win 10 Pro | 64-Bit | Upgrade (OEM)" )
Ose.create(is_enabled: 1, name: "Win 10 Pro | 32-Bit | Upgrade (OEM)" )
Ose.create(is_enabled: 1, name: "Win 10 Pro | 64-Bit | KMS" )
Ose.create(is_enabled: 1, name: "Win 10 Pro | 32-Bit | KMS " )
Ose.create(is_enabled: 1, name: "Win 10 Ent | 64-Bit | KMS" )
Ose.create(is_enabled: 1, name: "Win 10 Ent | 32-Bit | KMS" )
Ose.create(is_enabled: 1, name: "Win 10 Ent LTSB | 64-Bit | OEM" )
Ose.create(is_enabled: 1, name: "Other | Customer OS" )

ImageStatus.create(is_visible: 1, name: "Ship Image" )
ImageStatus.create(is_visible: 1, name: "Obsolete" )
ImageStatus.create(is_visible: 1, name: "Gold Image" )
ImageStatus.create(is_visible: 1, name: "Development" )
ImageStatus.create(is_visible: 1, name: "Test Image" )

Configuration.create(name: 'appTitle', value: 'Demo Depot - AutoZilla', description: 'This is the title that is displayed throughout the application.\r\n\r\nDefault: AutoZilla, The Rapid Clonezilla Image Deployment Framework')
Configuration.create(name: 'ldapBaseDn', value: 'OU=Workers,DC=amr,DC=corp,DC=intel,DC=com', description: 'This is the base DN for LDAP (Active Directory)\r\n\r\nDefault: OU=Workers,DC=amr,DC=corp,DC=intel,DC=com')
Configuration.create(name: 'ldapServer', value: 'amr.corp.intel.com', description: 'This is the LDAP (Active Directory) server address.\r\n\r\nDefault: amr.glb.intel.com')
Configuration.create(name: 'ldapMemberOfQuery', value: '(memberof=CN=IDD-TMEs,OU=Delegated,OU=Groups,DC=amr,DC=corp,DC=intel,DC=com)', description: 'This query dictates who can log-in. By default it only allows Intel Demo Depot TME''s (IDD-TMEs)\r\n\r\nDefault: (memberof=CN=IDD-TMEs,OU=Delegated,OU=Groups,DC=amr,DC=corp,DC=intel,DC=com)')
Configuration.create(name: 'clonezillaDefaultVersion', value: 'clonezilla-live-2.4.2-32-amd64', description: 'This is the default Clonezilla version.\n\nDefault: clonezilla-live-2.3.0-1-amd64-TESTING')
Configuration.create(name: 'imageBasePath', value: '/idd/Infrastructure/CloneZilla/NAMO.OR.Loan/Images/automation', description: 'This is the base image path on the file server (Samba/Windows share).\r\n\r\nDefault: /LCGhost/Clonezilla-images')
Configuration.create(name: 'imageServer', value: '10.23.79.74', description: 'This is the IP, Hostname or FQDN (Fully Qualified Domain Name) of the image server (Samba/Windows share).\r\n\r\nDefault: 10.23.88.13')
Configuration.create(name: 'squashfsFtpServer', value: '10.23.79.70',description: 'This is the IP, Hostname or FQDN (Fully Qualified Domain Name) of the FTP server hosting the Clonezilla live versions.\r\n\r\nIMPORTANT: Root path needs to follow this convention: /boot/grub/CloneZilla/\r\n\r\nDefault: 10.23.88.19')
Configuration.create(name: 'defaultCloneFlags', value: '-e2 -j2 -p choose',description: 'These are the default clone flags for Clonezilla that will appear in the text input when creating new images.\r\n\r\nDefault: -e2 -j2 -p')
Configuration.create(name: 'grubMenuPathPrefix', value: '\\\\boot\\\\grub',description: 'The menu path prefix for the Grub configuration files.\r\n\r\nDefault: \\\\boot\\\\grub')
Configuration.create(name: 'grubDownloadMenuSubdirectory', value: 'download/grub',description: 'This is the sub-directory under the grub configuration directory (defined in grubMenuPathPrefix) where all of the automation menu files will be stored when generated.Default: automation')
Configuration.create(name: 'imageServerUser', value: 'sys_iddclonezilla',description: 'This is the user account that has access to the images stored on the image server file share.\r\n\r\nDefault: iuser')
Configuration.create(name: 'imageServerPassword', value: '/root/.cifs.sys_iddclonezilla',description: 'This is the user account password that correlates to the imageServerUser account that has access to the images stored on the image server file share.\r\n\r\nDefault: Demo2000')
Configuration.create(name: 'grubAbsolutePath', value: '\\\\amr.corp.intel.com\\idd\\Infrastructure\\ADS3\\Boot\\OR.Grub',description: 'Absolute path to where the config files need to be saved.\n\nDefault: \\\\amr.corp.intel.com\\idd\\Infrastructure\\ADS3\\Boot\\OR.Grub')
Configuration.create(name: 'clonezillaVersionsSubdirectory', value: 'CloneZilla',description: 'The sub-directory under the Grub directory in which the different versions of Clonezilla are stored.Default: CloneZilla')
Configuration.create(name: 'AZKgrubAbsolutePath', value: 'D:\\AutoZillaKey\\live\\',description: 'This is the absolute path for the grub configuration files used by the AutoZillaKey')
Configuration.create(name: 'AZKclonezillaVersionsSubdirectory', value: 'CloneZilla',description: 'The sub-directory under the Grub directory in which the different versions of Clonezilla are stored. ')
Configuration.create(name: 'grubUploadMenuSubdirectory', value: 'upload/grub',description: 'This is the sub-directory under the grub configuration directory (defined in grubMenuPathPrefix) where all of the grub upload menu files will be stored when generated.Default: upload/grub')
Configuration.create(name: 'AZKgrubMenuPathPrefix', value: '/live/',description: '')
Configuration.create(name: 'AZKimageServer', value: 'amr.corp.intel.com',description: 'This is the IP, Hostname or FQDN (Fully Qualified Domain Name) of the image server (Samba/Windows share).\r\n\r\nDefault: 10.23.88.13')
Configuration.create(name: 'syslinuxDownloadMenuSubdirectory', value: 'download/syslinux',description: 'This is the sub-directory under the grub configuration directory (defined in grubMenuPathPrefix) where all of the automation menu files will be stored when generated.Default: automation')
Configuration.create(name: 'syslinuxUploadMenuSubdirectory', value: 'upload/syslinux',description: 'This is the sub-directory under the grub configuration directory (defined in grubMenuPathPrefix) where all of the grub upload menu files will be stored when generated.Default: upload/grub')
Configuration.create(name: 'AZKsyslinuxPath', value: '/syslinux/',description: '')
Configuration.create(name: 'AZKsyslinuxIncludeFile', value: 'graphics.conf',description: '')
Configuration.create(name: 'AZKsyslinuxUploadIncludeFile', value: 'graphics_upload.conf',description: '')
Configuration.create(name: 'AZKgrubUploadIncludeFile', value: 'graphics_upload.cfg',description: '')
Configuration.create(name: 'AZKgrubPath', value: '/EFI/boot/',description: '')
Configuration.create(name: 'AZKgrubIncludeFile', value: 'graphics.cfg',description: '')
Configuration.create(name: 'grubIncludeFile', value: 'graphics.cfg',description: '')
Configuration.create(name: 'grubUploadIncludeFile', value: 'graphics_upload.cfg',description: '')
Configuration.create(name: 'defaultCloneFlagsUpload', value: '-q2 -j2 -z1p -sc -p choose',description: 'These are the default upload clone flags for Clonezilla that will appear in the text input when creating new images.\r\n\r\nDefault: -q2 -j2 -z1p -sc -p true')

ClonezillaVersion.create(name: 'clonezilla-live-2.5.0-25-amd64', description: '', is_enabled: 1)
ClonezillaVersion.create(name: 'clonezilla-live-2.4.7-8-amd64', description: '', is_enabled: 1)
ClonezillaVersion.create(name: 'clonezilla-live-2.4.2-61-amd64', description: '', is_enabled: 1)
ClonezillaVersion.create(name: 'clonezilla-live-2.4.2-32-amd64', description: '', is_enabled: 1)
ClonezillaVersion.create(name: 'clonezilla-live-2.3.2-22-amd64', description: '', is_enabled: 1)
ClonezillaVersion.create(name: 'clonezilla-live-2.3.2-22-i686-pae', description: '', is_enabled: 1)

ImageType.create(is_enabled: 1, name: 'USDD')
ImageType.create(is_enabled: 1, name: 'OOBE')
ImageType.create(is_enabled: 1, name: 'Test')
ImageType.create(is_enabled: 1, name: 'Gold')
ImageType.create(is_enabled: 1, name: 'Custom_OS')
ImageType.create(is_enabled: 1, name: 'Event')
ImageType.create(is_enabled: 1, name: 'iDDR')